switch to using justfile for codegen of py-client

diff --git a/.github/actions/generate-openapi-py-client/action.yml b/.github/actions/generate-openapi-py-client/action.yml
--- a/.github/actions/generate-openapi-py-client/action.yml
+++ b/.github/actions/generate-openapi-py-client/action.yml
@@ -12,57 +12,38 @@ inputs:
   client_name:
     description: the name of the client library
     required: true
-  spec_file:
-    description: the openapi spec file to use when generating the client
-    required: false
-    default: client/openapi.json
-  config_file:
-    description: the config file to use when generating the client
-    required: true
-  output_dir:
-    description: the output directory for the client
-    required: true
-  custom_templates_dir:
-    description: the custom Jinja templates to be used when generating the client
-    required: true
 
 runs:
   using: composite
   steps:
-    - name: assert openapi spec is present
+    - name: assert uv.lock is present
       shell: bash
       run: |
-        [ -f ${{ inputs.spec_file }} ] || (echo "openapi spec is missing" 1>&2 && exit 1)
+        # require uv.lock to be present in the repository
+        [ -f uv.lock ] || (echo "uv.lock missing" 1>&2 && exit 1)
 
-    - name: assert generator config is present
+    - name: assert justfile is present
       shell: bash
       run: |
-        [ -f ${{ inputs.config_file }} ] || (echo "generator config for ${{ inputs.client_name }} is missing" 1>&2 && exit 1)
+        # require justfile to be present in the repository
+        [ -f justfile ] || (echo "justfile missing" 1>&2 && exit 1)
+
+    - name: install uv
+      uses: astral-sh/setup-uv@v7
+      with:
+        enable-cache: true
+        cache-dependency-glob: "uv.lock"
+
+    - name: install dependencies
+      run: |
+        uv sync --codegen
+
+    - uses: extractions/setup-just@v3
 
     - name: Generate Python Client
-      uses: openapi-generators/openapi-python-client-action@v2
-      with:
-        openapi-file: ${{ inputs.spec_file }}
-        config-file: ${{ inputs.config_file }}
-        extra-args: '--meta=uv, --custom-template-path=${{ inputs.custom_templates_dir }}, --output-path=${{ inputs.output_dir }}'
-
-    - name: remove attr generated models
       shell: bash
-      id: rm_models
       run: |
-        models_dir="$(echo client/py/*/models)"
-        rm -rf $models_dir/*
-        echo "models_dir=$models_dir" >> "$GITHUB_OUTPUT"
-
-    - uses: koxudaxi/datamodel-code-generator@0.55.0
-      with:
-        input: ${{inputs.spec_file}}
-        output: "${{ steps.rm_models.outputs.models_dir }}/__init__.py"
-        input-file-type: openapi
-        output-model-type: pydantic_v2.BaseModel
-        check: 'false'
-        extras: 'ruff'
-        extra-args: '--formatters ruff-format --formatters ruff-check --strict-nullable --use-default --use-default-kwargs --snake-case-field --capitalized-enum-members --use-annotated --use-decimal-for-multiple-of --field-constraints --use-union-operator --use-standard-collections --output-datetime-class datetime'
+        just generate-py
 
     - name: check for changes
       shell: bash
